### ISSUE TITLE
GetRequestMessage -> SetRequestMessage

### ISSUE THREAD

**Issue by samcarey** [lextm/sharpsnmp_docs#2]
Here it says to use GetRequestMessage where it should say SetRequestMessage:
https://docs.sharpsnmp.com/tutorials/v3-operations.html

The `int maxMessageSize` parameter also needs to be removed to match the newer API.

**Comment by lextm** [comment]
Thanks for pointing out the typo.

However, not sure where is "The int maxMessageSize parameter" you were referring to.
